env: "local"
storage_path: "STORAGE_PATH="user=user password=12345678 dbname=url_db host=localhost port=5436 sslmode=disable"
  "
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
